version: "3.6"

services:
  serpent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
    volumes:
      - .:/home/docker/app:rw
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis:

